### ISSUE TITLE
Cloudflareのデプロイでエラー出ました

### ISSUE THREAD

**Issue by nuovotaka** [otoyo/astro-notion-blog#4]
## 不具合の概要
何も変更していません。
Cloudflareでデプロイしてみました。エラー出ました。

## 再現方法
クローンしてCloudflareでデプロイしてみましたがエラー出ました。

デプロイまでできており公開された URL で不具合が確認できる場合には URL も記載します。

## エラーログ
2023-01-22T05:11:57.42198Z	Cloning repository...
2023-01-22T05:11:58.282906Z	From https://github.com/nuovotaka/astro-notion-blog
2023-01-22T05:11:58.283506Z	 * branch            429c0a02fa515c7f342216afe42efe73e0080631 -> FETCH_HEAD
2023-01-22T05:11:58.283718Z	
2023-01-22T05:11:58.338632Z	HEAD is now at 429c0a0 initial
2023-01-22T05:11:58.339157Z	
2023-01-22T05:11:58.483519Z	
2023-01-22T05:11:58.51169Z	Success: Finished cloning repository files
2023-01-22T05:11:59.203908Z	Installing dependencies
2023-01-22T05:11:59.215826Z	Python version set to 2.7
2023-01-22T05:12:02.73571Z	Downloading and installing node v16.13.0...
2023-01-22T05:12:03.159275Z	Downloading https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.xz...
2023-01-22T05:12:03.580235Z	Computing checksum with sha256sum
2023-01-22T05:12:03.707132Z	Checksums matched!
2023-01-22T05:12:07.90891Z	Now using node v16.13.0 (npm v8.1.0)
2023-01-22T05:12:08.301923Z	Started restoring cached build plugins
2023-01-22T05:12:08.315485Z	Finished restoring cached build plugins
2023-01-22T05:12:08.810047Z	Attempting ruby version 2.7.1, read from environment
2023-01-22T05:12:12.433213Z	Using ruby version 2.7.1
2023-01-22T05:12:12.796385Z	Using PHP version 5.6
2023-01-22T05:12:12.960641Z	5.2 is already installed.
2023-01-22T05:12:12.987387Z	Using Swift version 5.2
2023-01-22T05:12:12.988017Z	Started restoring cached node modules
2023-01-22T05:12:13.003762Z	Finished restoring cached node modules
2023-01-22T05:12:13.011566Z	Started restoring cached yarn cache
2023-01-22T05:12:13.025801Z	Finished restoring cached yarn cache
2023-01-22T05:12:13.045552Z	Installing yarn at version 1.22.4
2023-01-22T05:12:13.064391Z	[37mInstalling Yarn![0m
2023-01-22T05:12:13.0647Z	[36m> Downloading tarball...[0m
2023-01-22T05:12:13.108244Z	
2023-01-22T05:12:13.108592Z	[1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.pUAplRQmvC
2023-01-22T05:12:13.109202Z	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2023-01-22T05:12:13.109761Z	                                 Dload  Upload   Total   Spent    Left  Speed
2023-01-22T05:12:13.381239Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    79  100    79    0     0    290      0 --:--:-- --:--:-- --:--:--   291
2023-01-22T05:12:13.516413Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    93  100    93    0     0    228      0 --:--:-- --:--:-- --:--:-- 15500
2023-01-22T05:12:13.920563Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2023-01-22T05:12:14.250068Z	
100 1215k  100 1215k    0     0  1065k      0  0:00:01  0:00:01 --:--:-- 1065k
2023-01-22T05:12:14.250371Z	
2023-01-22T05:12:14.250669Z	[2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.pUAplRQmvC.asc
2023-01-22T05:12:14.285605Z	
100    83  100    83    0     0   2406      0 --:--:-- --:--:-- --:--:--  2406
2023-01-22T05:12:14.288292Z	
100    96  100    96    0     0   2583      0 --:--:-- --:--:-- --:--:--  2583
2023-01-22T05:12:14.29765Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2023-01-22T05:12:14.376502Z	
100  1028  100  1028    0     0   8198      0 --:--:-- --:--:-- --:--:--  8198
2023-01-22T05:12:14.42374Z	[36m> Verifying integrity...[0m
2023-01-22T05:12:14.468009Z	gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC using RSA key ID 69475BAA
2023-01-22T05:12:14.474165Z	gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
2023-01-22T05:12:14.476644Z	gpg: Note: This key has expired!
2023-01-22T05:12:14.476924Z	Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
2023-01-22T05:12:14.477109Z	     Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
2023-01-22T05:12:14.477738Z	[32m> GPG signature looks good[0m
2023-01-22T05:12:14.477962Z	[36m> Extracting to ~/.yarn...[0m
2023-01-22T05:12:14.572095Z	[36m> Adding to $PATH...[0m
2023-01-22T05:12:14.599738Z	[36m> We've added the following to your /opt/buildhome/.bashrc
2023-01-22T05:12:14.600053Z	> If this isn't the profile of your current shell then please add the following to your correct profile:
2023-01-22T05:12:14.600223Z	   
2023-01-22T05:12:14.600343Z	export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
2023-01-22T05:12:14.600458Z	[0m
2023-01-22T05:12:14.986451Z	[32m> Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.[0m
2023-01-22T05:12:15.389015Z	Installing NPM modules using Yarn version 1.22.4
2023-01-22T05:12:16.096626Z	yarn install v1.22.4
2023-01-22T05:12:16.184024Z	[1/4] Resolving packages...
2023-01-22T05:12:16.43334Z	[2/4] Fetching packages...
2023-01-22T05:12:31.832887Z	warning prettier-plugin-astro@0.7.2: The engine "pnpm" appears to be invalid.
2023-01-22T05:12:31.834802Z	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.83515Z	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.835968Z	info @esbuild/android-arm@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.836203Z	info "@esbuild/android-arm@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.836342Z	info @esbuild/android-arm@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.836469Z	info @esbuild/linux-loong64@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.836602Z	info "@esbuild/linux-loong64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.836758Z	info esbuild-android-64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.836874Z	info "esbuild-android-64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.836982Z	info esbuild-android-arm64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.837098Z	info "esbuild-android-arm64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.837216Z	info esbuild-android-arm64@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.837352Z	info esbuild-darwin-64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.837463Z	info "esbuild-darwin-64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.837589Z	info esbuild-darwin-arm64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.837696Z	info "esbuild-darwin-arm64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.837811Z	info esbuild-darwin-arm64@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.837917Z	info esbuild-freebsd-64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.838036Z	info "esbuild-freebsd-64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.838154Z	info esbuild-freebsd-arm64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.838262Z	info "esbuild-freebsd-arm64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.838373Z	info esbuild-freebsd-arm64@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.838489Z	info esbuild-linux-32@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.838601Z	info "esbuild-linux-32@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.838707Z	info esbuild-linux-arm@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.838816Z	info "esbuild-linux-arm@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.838923Z	info esbuild-linux-arm64@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.839029Z	info "esbuild-linux-arm64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.839143Z	info esbuild-linux-mips64le@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.839259Z	info "esbuild-linux-mips64le@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.839374Z	info esbuild-linux-ppc64le@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.839495Z	info "esbuild-linux-ppc64le@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.839608Z	info esbuild-linux-riscv64@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.839721Z	info "esbuild-linux-riscv64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.839826Z	info esbuild-linux-s390x@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.839931Z	info "esbuild-linux-s390x@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.840046Z	info esbuild-netbsd-64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.840168Z	info "esbuild-netbsd-64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.840288Z	info esbuild-openbsd-64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.840398Z	info "esbuild-openbsd-64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.840514Z	info esbuild-sunos-64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.840625Z	info "esbuild-sunos-64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.840732Z	info esbuild-windows-32@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.840839Z	info "esbuild-windows-32@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.840955Z	info esbuild-windows-32@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.841067Z	info esbuild-windows-64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.841181Z	info "esbuild-windows-64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.841288Z	info esbuild-windows-arm64@0.15.18: The platform "linux" is incompatible with this module.
2023-01-22T05:12:31.841405Z	info "esbuild-windows-arm64@0.15.18" is an optional dependency and failed compatibility check. Excluding it from installation.
2023-01-22T05:12:31.841526Z	info esbuild-windows-arm64@0.15.18: The CPU architecture "x64" is incompatible with this module.
2023-01-22T05:12:31.850264Z	[3/4] Linking dependencies...
2023-01-22T05:12:31.852252Z	warning " > @astrojs/react@1.2.2" has unmet peer dependency "@types/react@^17.0.50 || ^18.0.21".
2023-01-22T05:12:31.852679Z	warning " > @astrojs/react@1.2.2" has unmet peer dependency "@types/react-dom@^17.0.17 || ^18.0.6".
2023-01-22T05:12:31.854492Z	warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
2023-01-22T05:12:42.115097Z	[4/4] Building fresh packages...
2023-01-22T05:12:43.577705Z	Done in 27.49s.
2023-01-22T05:12:43.607966Z	NPM modules installed using Yarn
2023-01-22T05:12:43.900672Z	Installing Hugo 0.54.0
2023-01-22T05:12:44.592211Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2023-01-22T05:12:44.596157Z	Started restoring cached go cache
2023-01-22T05:12:44.615749Z	Finished restoring cached go cache
2023-01-22T05:12:44.757346Z	go version go1.14.4 linux/amd64
2023-01-22T05:12:44.773234Z	go version go1.14.4 linux/amd64
2023-01-22T05:12:44.777001Z	Installing missing commands
2023-01-22T05:12:44.777263Z	Verify run directory
2023-01-22T05:12:44.777404Z	Executing user command: npm run build
2023-01-22T05:12:45.227739Z	
2023-01-22T05:12:45.228096Z	> astro-notion-blog@0.1.0 build
2023-01-22T05:12:45.228257Z	> astro build
2023-01-22T05:12:45.228388Z	
2023-01-22T05:12:47.230115Z	05:12:47 AM [build] output target: static
2023-01-22T05:12:47.230546Z	05:12:47 AM [build] Collecting build info...
2023-01-22T05:12:47.231764Z	05:12:47 AM [build] Completed in 27ms.
2023-01-22T05:12:47.232828Z	05:12:47 AM [build] Building static entrypoints...
2023-01-22T05:12:49.561353Z	05:12:49 AM [build] Completed in 2.33s.
2023-01-22T05:12:49.561725Z	
2023-01-22T05:12:49.56187Z	 building client 
2023-01-22T05:12:55.586029Z	
2023-01-22T05:12:55.586354Z	(!) Some chunks are larger than 500 KiB after minification. Consider:
2023-01-22T05:12:55.586519Z	- Using dynamic import() to code-split the application
2023-01-22T05:12:55.586643Z	- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
2023-01-22T05:12:55.586756Z	- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
2023-01-22T05:12:55.586871Z	Completed in 6.02s.
2023-01-22T05:12:55.587064Z	
2023-01-22T05:12:55.587289Z	
2023-01-22T05:12:55.58743Z	 generating static routes 
2023-01-22T05:12:56.445544Z	▶ src/pages/index.astro
2023-01-22T05:12:56.459601Z	  └─ /index.html (+14ms)
2023-01-22T05:12:56.459986Z	▶ src/pages/blog/index.astro
2023-01-22T05:12:57.815651Z	 error   Cannot read properties of undefined (reading 'files')
2023-01-22T05:12:57.816139Z	  File:
2023-01-22T05:12:57.816322Z	    /opt/buildhome/repo/node_modules/astro/dist/runtime/server/render/page.js:89:30
2023-01-22T05:12:57.816445Z	  Code:
2023-01-22T05:12:57.816573Z	    88 |   }
2023-01-22T05:12:57.816699Z	    > 89 |   const factoryReturnValue = await componentFactory(result, props, children);
2023-01-22T05:12:57.81681Z	         |                              ^
2023-01-22T05:12:57.816919Z	      90 |   const factoryIsHeadAndContent = isHeadAndContent(factoryReturnValue);
2023-01-22T05:12:57.817029Z	      91 |   if (isRenderTemplateResult(factoryReturnValue) || factoryIsHeadAndContent) {
2023-01-22T05:12:57.817165Z	      92 |     await bufferHeadContent(result);
2023-01-22T05:12:57.817322Z	  Stacktrace:
2023-01-22T05:12:57.817492Z	TypeError: Cannot read properties of undefined (reading 'files')
2023-01-22T05:12:57.817655Z	    at _buildPost (file:///opt/buildhome/repo/dist/entry.mjs?time=1674364375586:2360:39)
2023-01-22T05:12:57.817783Z	    at file:///opt/buildhome/repo/dist/entry.mjs?time=1674364375586:1953:92
2023-01-22T05:12:57.817898Z	    at Array.map (<anonymous>)
2023-01-22T05:12:57.818011Z	    at getAllPosts (file:///opt/buildhome/repo/dist/entry.mjs?time=1674364375586:1953:72)
2023-01-22T05:12:57.818129Z	    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-01-22T05:12:57.818237Z	    at async getNumberOfPages (file:///opt/buildhome/repo/dist/entry.mjs?time=1674364375586:2001:20)
2023-01-22T05:12:57.818347Z	    at async Promise.all (index 3)
2023-01-22T05:12:57.818456Z	    at async file:///opt/buildhome/repo/dist/entry.mjs?time=1674364375586:2609:53
2023-01-22T05:12:57.818586Z	    at async renderPage (file:///opt/buildhome/repo/node_modules/astro/dist/runtime/server/render/page.js:89:30)
2023-01-22T05:12:57.818706Z	    at async renderPage (file:///opt/buildhome/repo/node_modules/astro/dist/core/render/core.js:86:20)
2023-01-22T05:12:57.818825Z	
2023-01-22T05:12:57.858695Z	Failed: build command exited with code: 1
2023-01-22T05:12:58.739072Z	Failed: an internal error occurred

## リポジトリとブランチ名
もし Fork した easy-notion-blog でエラーが発生している場合には、あなたのリポジトリの URL とブランチ名を記載します。

## デスクトップ環境
 - OS: [ MacOS]
 - ブラウザ: [Brave]
 - ブラウザのバージョン: [1.47.171]

**Comment by nuovotaka** [comment]
easy-notion-blogで使用していたNotionの'OGImage'を'FeaturedImage'に変更したら記事が表示されるようになりました。

**Comment by otoyo** [comment]
https://github.com/otoyo/astro-notion-blog/issues/3 と同じエラーのように思われます。

**Comment by otoyo** [comment]
https://github.com/otoyo/astro-notion-blog/pull/5 で修正したので取り込んで試していただけますでしょうか。

**Comment by nuovotaka** [comment]
https://astro-notion-blog-8hf.pages.dev/
デプロイできました。
記事も表示されています。埋め込み画像も表示されています。最も画像サイズをダウンして圧縮したものを利用しておりますが。。。１画像100KB程度以下にしてみました。

**Comment by otoyo** [comment]
ご確認ありがとうございます。
画像サイズは1MB程度以内であれば問題なく表示できるかと思います。
